### ISSUE TITLE
Use fetch instead of xhr 

### ISSUE THREAD

**Issue by codeprospect** [petershivachi/joke-generator#2]
### Fetch is a bit better

I believe fetch is better since it makes it easier to make asynchronous requests and handle responses better

**Comment by petershivachi** [comment]
Thanks for the review bro..actually I just needed a refresher with AJAX and
XHR but I agree with you Fetch is the latest technology and its dope
because it's part of vanilla (corejs)
You may also want to check out superagent and axios which are external
libraries.
